## Mean

In [2]:
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6])
print("Mean: ", np.mean(data))

Mean:  3.5


In [3]:
import numpy as np

data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

print("sum(data):", np.sum(data))

print("mean(data):", np.mean(data))
print("mean(data),axis=1:", np.mean(data, axis=1))
print("mean(data),axis=0:", np.mean(data, axis=0))

sum(data): 45
mean(data): 5.0
mean(data),axis=1: [2. 5. 8.]
mean(data),axis=0: [4. 5. 6.]


## for later

In [4]:
data = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

print(data.shape)
print("sum(data):", np.sum(data))

print()
print("mean(data):", np.mean(data), "\n")
print("mean(data),axis=1:\n", np.mean(data, axis=1), "\n")
print("mean(data),axis=0:\n", np.mean(data, axis=0))

(2, 3, 3)
sum(data): 171

mean(data): 9.5 

mean(data),axis=1:
 [[ 4.  5.  6.]
 [13. 14. 15.]] 

mean(data),axis=0:
 [[ 5.5  6.5  7.5]
 [ 8.5  9.5 10.5]
 [11.5 12.5 13.5]]


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(np.sum(arr))

45
