# Array Manipulation

## 1. Reshaping Array
- Reshaping Array: changing the dimensions of array.

## 2. Array Transposition

In [61]:
# Transposing 2-D array

import numpy as np
arr2d = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [15, 14, 15, 16, 17, 18]
])

arr_trans = arr2d.T

print("Original Array:\n", arr2d, "\n")
print("Original Array Shape:", arr2d.shape)

print()
print("Transposed Array:\n", arr_trans, "\n")
print("Transposed Array (shape):", arr_trans.shape)

Original Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [15 14 15 16 17 18]] 

Original Array Shape: (3, 6)

Transposed Array:
 [[ 1  7 15]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]
 [ 6 12 18]] 

Transposed Array (shape): (6, 3)


In [58]:
# Transposing 2-D array

import numpy as np
arr2d = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160],
    [170, 180, 190, 200]
])

arr_trans = np.transpose(arr2d)

print("Original Array:\n", arr2d, "\n")
print("Original Array Shape:", arr2d.shape)

print()
print("Transposed Array:\n", arr_trans, "\n")
print("Transposed Array (shape):", arr_trans.shape)

Original Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]
 [170 180 190 200]] 

Original Array Shape: (5, 4)

Transposed Array:
 [[ 10  50  90 130 170]
 [ 20  60 100 140 180]
 [ 30  70 110 150 190]
 [ 40  80 120 160 200]] 

Transposed Array (shape): (4, 5)


In [57]:
# Transposing a 3-D array

import numpy as np
arr3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ]
])

arr3d_t = arr3d.T

print("Original 3-D Array:\n", arr3d, "\n")
print("Original Array Shape:", arr3d.shape)

print()
print("Transposed 3-D Array:\n", arr3d_t, "\n")
print("Transposed Array Shape:", arr3d_t.shape)

Original 3-D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]] 

Original Array Shape: (1, 3, 4)

Transposed 3-D Array:
 [[[ 1]
  [ 5]
  [ 9]]

 [[ 2]
  [ 6]
  [10]]

 [[ 3]
  [ 7]
  [11]]

 [[ 4]
  [ 8]
  [12]]] 

Transposed Array Shape: (4, 3, 1)


In [56]:
# Transposing a 3-D array

import numpy as np
arr3d = np.array([
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]
    ], 
    [
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]
    ],
    [
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 50]
    ]
])

arr3d_t = np.transpose(arr3d)

print("Original 3-D Array:\n", arr3d, "\n")
print("Original Array Shape:", arr3d.shape)

print()
print("Transposed 3-D Array:\n", arr3d_t, "\n")
print("Transposed Array Shape:", arr3d_t.shape)

Original 3-D Array:
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 50]]] 

Original Array Shape: (3, 4, 5)

Transposed 3-D Array:
 [[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 50]]] 

Transposed Array Shape: (5, 4, 3)
