### Initial Placeholders

#### `np.zeros()`

In [3]:
import numpy as np

arr8 = np.zeros(5)

print(arr8)
print(arr8.dtype)

[0. 0. 0. 0. 0.]
float64


In [4]:
arr8 = np.zeros(5, dtype='int')

print(arr8)

[0 0 0 0 0]


In [5]:
arr9 = np.zeros((3, 4))
# arr9.shape
# arr9.ndim
print(arr9)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
arr9 = np.zeros((3, 4, 4),dtype=int)
print(arr9)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


#### `np.ones()`

In [7]:
arr10 = np.ones((3, 4, 4), dtype=int)
print(arr10)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


#### `np.eye()` /identity matrix

In [8]:
arr11 = np.eye((4), dtype=int)
print(arr11)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [12]:
arr12 = np.eye(3,5)
print(arr12)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
