# Random Arrays

#### x. `np.random.rand()`

In [1]:
import numpy as np

arr17 = np.random.rand(5) # between 0-1 (uniform distribution) 
print(arr17)

[0.08594614 0.73838572 0.40554867 0.1927045  0.08038869]


In [2]:
arr18 = np.random.rand(5, 5) # between 0-1
print(arr18)

[[0.91884613 0.48539468 0.28339388 0.54659271 0.43567695]
 [0.10846234 0.92158078 0.78168226 0.53696264 0.68729853]
 [0.3735263  0.40401538 0.34020705 0.68914477 0.68655063]
 [0.02399109 0.45835408 0.0038711  0.32218775 0.02400393]
 [0.91598645 0.3055703  0.87536345 0.97858411 0.63447647]]


In [3]:
arr19 = np.random.rand(2, 5, 5) # between 0-1
print(arr19)

[[[0.50545227 0.24955975 0.57371954 0.824945   0.41040715]
  [0.50533157 0.02611104 0.94005391 0.81590154 0.97859932]
  [0.13561977 0.8115202  0.18649053 0.11134472 0.41073421]
  [0.45108198 0.54456583 0.10264831 0.21188462 0.9395489 ]
  [0.86373627 0.1452179  0.59839573 0.91826889 0.39773267]]

 [[0.5016912  0.19727196 0.26529755 0.99525677 0.62496735]
  [0.66863426 0.11771281 0.66017623 0.42000983 0.09228681]
  [0.88468643 0.59575204 0.30991626 0.10284049 0.87133714]
  [0.94072401 0.98606037 0.30698379 0.91929727 0.8808242 ]
  [0.67661467 0.31462696 0.32816148 0.08825818 0.67790346]]]


#### x. `np.random.randint()`

In [4]:
arr20 = np.random.randint(1, 10, size=10, dtype=np.uint8) # lowest (inclusive), highest (exclusive)
print(arr20)

[6 7 5 6 9 6 7 1 4 9]


In [6]:
arr21 = np.random.randn(10) # normal distribution (most numbers are close to 0, fewer)
print(arr21)

[-1.11188012  0.31890218  0.27904129  1.01051528 -0.58087813 -0.52516981
 -0.57138017 -0.92408284 -2.61254901  0.95036968]


In [5]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]
