In [53]:
import psutil
battery = psutil.sensors_battery()

if battery is not None:
    print("Battery Percentage:", battery.percent, "%")
    print("Power plugged in:", battery.power_plugged)

    def convertTime(seconds):
        minutes, seconds = divmod (seconds, 60)
        hours, minutes = divmod(minutes, 60)
        return "%d:%02d:%02d" % (hours, minutes, seconds)

    print("Battery remaining time:", convertTime(battery.secsleft))
else:
    print("No battery information available.")

Battery Percentage: 100 %
Power plugged in: True
Battery remaining time: -1:59:58


In [54]:
import numpy as np
arr1 = np.zeros(5) # 1-D 
arr1i = np.zeros(5, dtype=int) # 

print(arr1)
print(arr1i)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


### np.ones()

In [55]:
import numpy as np
arr1 = np.ones(5) # 1-D 
arr1i = np.ones(5, dtype=int) # 

print(arr1)
print(arr1i)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]


In [56]:
import numpy as np
arr3 = np.ones((4, 5), dtype=int) # 2-D
print(arr3)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [57]:
import numpy as np
arr4 = np.ones((3, 4, 5), dtype=int) # 3-D 
print(arr4)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [58]:

arr7 = np.ones((2, 3, 4, 5), dtype=int) # 4-D
print(arr7)

[[[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]]


In [59]:
import numpy as np
# Create a 2D array (5x6) with numbers from 1 to 30
arr2d = np.arange(1, 31).reshape(5, 6)
print("np.arange(1, 31).reshape(5, 6):\n", arr2d)

np.arange(1, 31).reshape(5, 6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [60]:
import numpy as np
# Create a 4D array sized (2, 3, 4, 5) with numbers from 1 to 120
arr4d = np.arange(1, 121).reshape(2, 3, 4, 5)
print("np.arange(1, 121).reshape(2, 3, 4, 5):\n", arr4d)

np.arange(1, 121).reshape(2, 3, 4, 5):
 [[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]


In [61]:
arr2 = np.arange(1, 121).reshape(2, 3, 4, 5)
arr2

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])

### Key Array Attributes

In [62]:
import numpy as np
arr1d = np.zeros(5)
arr2d = np.zeros((4, 5), dtype=int)
arr3d = np.zeros((3, 4, 5), dtype=int)
arr4d = np.zeros((2, 3, 4, 5), dtype=int)

print("Array Items:\n", arr1d, "\n")
print("Array Dimension:", arr1d.ndim)
print("Array Shape:", arr1d.shape)
print("Array Size:", arr1d.size)
print("Array Datatype:", arr1d.dtype)
print("Array Item Size:", arr1d.itemsize)
print("Array nbytes:", arr1d.nbytes)
print("Array Data:", arr1d.data)

Array Items:
 [0. 0. 0. 0. 0.] 

Array Dimension: 1
Array Shape: (5,)
Array Size: 5
Array Datatype: float64
Array Item Size: 8
Array nbytes: 40
Array Data: <memory at 0x00000294E8776740>


In [63]:
import numpy as np
arr1d = np.zeros(5, dtype=int)

print("Array Items:\n", arr1d, "\n")
print("Array Dimension:", arr1d.ndim)
print("Array Shape:", arr1d.shape)
print("Array Size:", arr1d.size)
print("Array Datatype:", arr1d.dtype)
print("Array Item Size:", arr1d.itemsize)
print("Array nbytes:", arr1d.nbytes)
print("Array Data:", arr1d.data)

Array Items:
 [0 0 0 0 0] 

Array Dimension: 1
Array Shape: (5,)
Array Size: 5
Array Datatype: int64
Array Item Size: 8
Array nbytes: 40
Array Data: <memory at 0x00000294E8776500>


In [64]:
import numpy as np
arr2d = np.zeros((4, 5), dtype=int)

print("Array Items:\n", arr2d, "\n")
print("Array Dimension:", arr2d.ndim)
print("Array Shape:", arr2d.shape)
print("Array Size:", arr2d.size)
print("Array Datatype:", arr2d.dtype)
print("Array Item Size:", arr2d.itemsize)
print("Array nbytes:", arr2d.nbytes)
print("Array Data:", arr2d.data)

Array Items:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 

Array Dimension: 2
Array Shape: (4, 5)
Array Size: 20
Array Datatype: int64
Array Item Size: 8
Array nbytes: 160
Array Data: <memory at 0x00000294E8D73920>


In [65]:
import numpy as np
arr3d = np.zeros((3, 4, 5), dtype=int)

print("Array Items:\n", arr3d, "\n")
print("Array Dimension:", arr3d.ndim)
print("Array Shape:", arr3d.shape)
print("Array Size:", arr3d.size)
print("Array Datatype:", arr3d.dtype)
print("Array Item Size:", arr3d.itemsize)
print("Array nbytes:", arr3d.nbytes)
print("Array Data:", arr3d.data)

Array Items:
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]] 

Array Dimension: 3
Array Shape: (3, 4, 5)
Array Size: 60
Array Datatype: int64
Array Item Size: 8
Array nbytes: 480
Array Data: <memory at 0x00000294E98CC310>


In [66]:
import numpy as np
arr4d = np.zeros((2, 3, 4, 5), dtype=int)

print("Array Items:\n", arr4d, "\n")
print("Array Dimension:", arr4d.ndim)
print("Array Shape:", arr4d.shape)
print("Array Size:", arr4d.size)
print("Array Datatype:", arr4d.dtype)
print("Array Item Size:", arr4d.itemsize)
print("Array nbytes:", arr4d.nbytes)
print("Array Data:", arr4d.data)

Array Items:
 [[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]] 

Array Dimension: 4
Array Shape: (2, 3, 4, 5)
Array Size: 120
Array Datatype: int64
Array Item Size: 8
Array nbytes: 960
Array Data: <memory at 0x00000294E98BB040>


#### arr.dtype

In [75]:
arr1 = np.array(["Kathmandu", "Surkhet", "Nuwakot"])
arr2 = np.array([1, 5, 78, 12])
arr3 = np.array([1.6, 86.6, 78.1])

print("arr1 Items:", arr1)
print("arr1 Data Types:", arr1.dtype)

print("\narr2 Items:", arr2)
print("arr2 Data Types:", arr2.dtype)

print("\narr3 Items:", arr3)
print("arr3 Data Types:", arr3.dtype)

arr1 Items: ['Kathmandu' 'Surkhet' 'Nuwakot']
arr1 Data Types: <U9

arr2 Items: [ 1  5 78 12]
arr2 Data Types: int64

arr3 Items: [ 1.6 86.6 78.1]
arr3 Data Types: float64
